travis:
  secure:
    BINSTAR_TOKEN: YnK2rBOfuPqk4TDvOKysILnD1HK3ys+ppzPhE+iBZE0+n0DPAOFq1miBYB/5GlF8OrdBDRkpNP8IHQHRsCkQKiA523esdSPUVGcKc2Ci1drf5+Gkm0Wl82jhi/wqidM9OSkpR3Pk2LQJhV1IH0lEQ5rnm046B8Pmly5i7umKJhXd44qTlIYvk3Zhavfg5OjXnE72E9WHmUAilY21bJPNo+Bt0RBf9+u4tQDOsNssUyBRQ7+UEtReXnBGXYm0ybng6509ATO0hZjTrnyL6QDd5D4lIGRIZTw+a73PVNaG6su81s7pivTtLGVJyTQ8koHj9RW0phk5G5OQwOhTRWuyGsjZeumz49tQ9Wu0RfUjwvsyLC3iXJ5704o2IusuyQrkq9+v1F6k1g8QC3RL7DT9PNMdtayqm/OyR3qTrb0vqr4OJz/EUIE+Vgw2lEGSApW/xq8BEdL0HbQleAYhAN1gd+XsGmerNKmH6I1Iueir9y/a6YsM7XA/Bg7SMReOevQKwSqHb0Jx67nJqZT+NoGfkUCYDh4MtXIzRN7y0OLLp9DbaAEj7fHeQxqxv8L57dv6Tjos2aoBiqhZ6bfEpPD9hCAF+vvE2IuhrgyWi3Yn82RP/tsgDyvk7aULAUa30up/O1ErB+IZZz6dmnHIOruJ5tw7t4NbWpbim5nRhg0s+mM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
