travis:
  secure:
    BINSTAR_TOKEN: IWp4vI6dfa1y/5zb6aMY2j1dR6p7WySffc2ZW28Vnaxjz+66qWT89Y18ppQkqMweLGnaiCstB0OqLPkR8SfE/g87M8HpaFoB1nqlV2r45jget8R9pjgxX+mgo1GBF9Vq1PrL0Fo+CFqtoZO17Bln4MI4k0G6SAiuALvAQN8HMCMyw/t2zf054nAtbQvBtA8sZU/FoaOMJqoHxqH2JG5ibdeahGkTS/5GmwPB1bYLgzeUV5tqWDvmgyNVGUDw90nsENezuHZSeYLdkkItq1oYGX8SNAQ/Gido1VgBovOPiOdpI7ln26eoCr9nT/CZmG06ppDn6YW2S2SliEi3H58CjWo2o61yCaiQclxBqpakH+5+J0UN5fRFK2bvgGNhL/RU5k5vcfVnAyINT6lWlydnAIrSwdv/3OVlDeH0YwWUDHUJC59ski/q6FqNSDKKP1XCGwHsPyxyrXZuizNUHOM2+XJeqgiw0mwIr8kPRt78Cl802B/i00F8MHA5FGOei2iycMIMIq5c01vXKqtANBgL/dr9C5YfOsLQfi9lI/R2CcCIdBjI2w4Za5WqImlv0QrgAkNPsF+84cHBac0dM8TaKIDaV3Fe+IlmkSTjI8f9CMa+dwmgaLM0dhFfTB0fWbr7T7+GlBsRwv3YhXplLH4Kr9/lt4MSALPMaCG9pZtXiJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
